name: list repos
on: [push]
jobs:
  list of repos:
    runs-on: ubuntu-latest
    steps:
      - name: list of repos
        run: |
          echo "${{github.token}}"
          
          
      - name : passing the token 
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: echo "${{github.token}}" "\
          -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/orgs/chaituorgg/repos
          
