name: Testworkflow

on : [push]

jobs:
  newjob:
    runs-on: ubuntu-latest
    
    steps:
     - name: echo a string
       run: echo "Hello world"
       
     - name: 3 line script
       run: |
        node -v
        pwd
        ls -la
        
  JOB3:
    runs-on: ubuntu-latest
    steps:
      - name: check refered action 
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: chaitanya
        
      - name: Outout of step1 
        run: echo "{{ steps.greet.outputs.time}}"
        
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name: Tets ls
        run: |
          ls
          ls -la
          pwd
          
    
        

        
        
        
  
        
  
