name: shell commands

#define events 
on: [push]

#jobs 

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "Hello world"
      - name : multiline commands
        run: |
          git --version
          pwd
  
  job2:
    runs-on: windows-latest
    needs: ["Job1"]
    steps:
      - name: new file 
        run: |
          pwd 
          echo "please find path"
  job3:
    runs-on: ubuntu-latest
    steps:
    - name: ck
      run: |
        pwd
        git --version
        
    - name : checkout repository 
      id: greet
      uses: actions/hello-world-javascript-action@main
      with:
        what to greet: ck
    
    - name: output display
      run: echo "${{steps.greet.outputs.time}}"
      
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: test long list in VM 
        run: |
          ls
          pwd
          
      - name: checkout last commit of repo and fectch the code
        uses: actions/checkout@v1
      - name: check repo
        run: |
          git log 
          pwd
          ls -a
          ls -ltr
          df -h
        
  
        

    
  
