name: sample2 workflow

on: 
  push:
    branches-ignore:
      - master
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step for 1st PR
         run: | 
          git log 
           
    
