name: shell commands

#define events 
on: [push]

#jobs 

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "Hello world"
      - name : multiline commands
        run: |
          git --version
          pwd
  
  job2:
    runs-on: windows-latest
    needs: ["Job1"]
    steps:
      - name: new file 
        run: |
          pwd 
          echo "please find path"

    
  
